package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"encoding/json"
	"fmt"
	"poc-collaborative-filter/graph/generated"
	"poc-collaborative-filter/graph/model"
	"poc-collaborative-filter/internal/domain"
	"poc-collaborative-filter/internal/repository"
)

// Traits is the resolver for the traits field.
func (r *customerResolver) Traits(ctx context.Context, obj *domain.Customer) (*domain.CustomerTraits, error) {
	traits, err := obj.GetTraits()
	if err != nil {
		return nil, err
	}
	return traits, nil
}

// CreateCustomer is the resolver for the createCustomer field.
func (r *mutationResolver) CreateCustomer(ctx context.Context, input model.CreateCustomerInput) (*domain.Customer, error) {
	customer := &domain.Customer{
		Name:    input.Name,
		Phone:   input.Phone,
		Segment: input.Segment,
		Status:  input.Status,
	}

	// Handle optional email
	if input.Email != nil {
		customer.Email = *input.Email
	}

	// Handle optional risk profile
	if input.RiskProfile != nil {
		customer.RiskProfile = *input.RiskProfile
	}

	// Convert traits input if provided
	if input.Traits != nil {
		traits := domain.CustomerTraits{
			Personality: input.Traits.Personality,
			Preferences: input.Traits.Preferences,
			Tags:        input.Traits.Tags,
		}

		// Handle optional notes
		if input.Traits.Notes != nil {
			traits.Notes = *input.Traits.Notes
		}

		// Convert properties
		if input.Traits.Properties != nil {
			traits.Properties = make([]domain.TraitProperty, len(input.Traits.Properties))
			for i, prop := range input.Traits.Properties {
				traits.Properties[i] = domain.TraitProperty{
					Key:   prop.Key,
					Value: prop.Value,
					Type:  prop.Type,
				}
			}
		}

		// Convert related persons
		if input.Traits.RelatedPersons != nil {
			traits.RelatedPersons = make([]domain.RelatedPerson, len(input.Traits.RelatedPersons))
			for i, person := range input.Traits.RelatedPersons {
				traits.RelatedPersons[i] = domain.RelatedPerson{
					Name:         person.Name,
					Relationship: person.Relationship,
					Phone:        person.Phone,
					Email:        person.Email,
				}
			}
		}

		if err := customer.SetTraits(traits); err != nil {
			return nil, err
		}
	}

	return r.customerService.CreateCustomer(ctx, customer)
}

// UpdateCustomer is the resolver for the updateCustomer field.
func (r *mutationResolver) UpdateCustomer(ctx context.Context, id string, input model.UpdateCustomerInput) (*domain.Customer, error) {
	// Get existing customer
	existing, err := r.customerService.GetCustomer(ctx, id)
	if err != nil {
		return nil, err
	}

	// Update fields if provided (GraphQL input uses pointers for optional fields)
	if input.Name != nil {
		existing.Name = *input.Name
	}
	if input.Email != nil {
		existing.Email = *input.Email
	}
	if input.Phone != nil {
		existing.Phone = input.Phone
	}
	if input.Segment != nil {
		existing.Segment = *input.Segment
	}
	if input.Status != nil {
		existing.Status = *input.Status
	}
	if input.RiskProfile != nil {
		existing.RiskProfile = *input.RiskProfile
	}

	// Update traits if provided
	if input.Traits != nil {
		traits := domain.CustomerTraits{
			Personality: input.Traits.Personality,
			Preferences: input.Traits.Preferences,
			Tags:        input.Traits.Tags,
		}

		// Handle optional notes
		if input.Traits.Notes != nil {
			traits.Notes = *input.Traits.Notes
		}

		if input.Traits.Properties != nil {
			traits.Properties = make([]domain.TraitProperty, len(input.Traits.Properties))
			for i, prop := range input.Traits.Properties {
				traits.Properties[i] = domain.TraitProperty{
					Key:   prop.Key,
					Value: prop.Value,
					Type:  prop.Type,
				}
			}
		}

		if input.Traits.RelatedPersons != nil {
			traits.RelatedPersons = make([]domain.RelatedPerson, len(input.Traits.RelatedPersons))
			for i, person := range input.Traits.RelatedPersons {
				traits.RelatedPersons[i] = domain.RelatedPerson{
					Name:         person.Name,
					Relationship: person.Relationship,
					Phone:        person.Phone,
					Email:        person.Email,
				}
			}
		}

		if err := existing.SetTraits(traits); err != nil {
			return nil, err
		}
	}

	return r.customerService.UpdateCustomer(ctx, id, existing)
}

// DeleteCustomer is the resolver for the deleteCustomer field.
func (r *mutationResolver) DeleteCustomer(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteCustomer - deleteCustomer"))
}

// DismissRecommendation is the resolver for the dismissRecommendation field.
func (r *mutationResolver) DismissRecommendation(ctx context.Context, id string) (*domain.Recommendation, error) {
	return r.recommendationService.DismissRecommendation(ctx, id)
}

// AcceptRecommendation is the resolver for the acceptRecommendation field.
func (r *mutationResolver) AcceptRecommendation(ctx context.Context, id string) (*domain.Recommendation, error) {
	return r.recommendationService.AcceptRecommendation(ctx, id)
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, id string) (*domain.Customer, error) {
	return r.customerService.GetCustomer(ctx, id)
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context, filter *model.CustomerFilter, limit *int, offset *int) (*model.CustomerConnection, error) {
	defaultLimit := 20
	if limit != nil {
		defaultLimit = *limit
	}
	defaultOffset := 0
	if offset != nil {
		defaultOffset = *offset
	}

	// Convert GraphQL filter to repository filter (clean architecture)
	repoFilter := repository.CustomerFilter{}
	if filter != nil {
		repoFilter.Segment = filter.Segment
		repoFilter.Status = filter.Status
		repoFilter.RiskProfile = filter.RiskProfile
		repoFilter.Search = filter.Search
	}

	customers, total, err := r.customerService.GetCustomers(ctx, repoFilter, defaultLimit, defaultOffset)
	if err != nil {
		return nil, err
	}

	return &model.CustomerConnection{
		Nodes:      customers,
		TotalCount: int(total),
	}, nil
}

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, customerID string, typeArg *domain.RecommendationType, limit *int) ([]*domain.Recommendation, error) {
	defaultLimit := 10
	if limit != nil {
		defaultLimit = *limit
	}

	return r.recommendationService.GetRecommendations(ctx, customerID, typeArg, defaultLimit)
}

// SimilarCustomers is the resolver for the similarCustomers field.
func (r *queryResolver) SimilarCustomers(ctx context.Context, customerID string, limit *int) ([]*model.SimilarCustomer, error) {
	defaultLimit := 10
	if limit != nil {
		defaultLimit = *limit
	}

	// Call collaborative filter service
	similar, err := r.collaborativeFilterService.FindSimilarCustomers(ctx, customerID, defaultLimit)
	if err != nil {
		return nil, err
	}

	// Convert to GraphQL model
	result := make([]*model.SimilarCustomer, len(similar))
	for i, sim := range similar {
		result[i] = &model.SimilarCustomer{
			Customer:        sim.Customer,
			SimilarityScore: sim.Score.Score,
			Weights: &model.SimilarityWeights{
				Personal:       sim.Score.Weights.Personal,
				Survey:         sim.Score.Weights.Survey,
				ActivityAccess: sim.Score.Weights.ActivityAccess,
				Transaction:    sim.Score.Weights.Transaction,
			},
		}
	}

	return result, nil
}

// GenerateRecommendations is the resolver for the generateRecommendations field.
func (r *queryResolver) GenerateRecommendations(ctx context.Context, customerID string, typeArg domain.RecommendationType) ([]*domain.Recommendation, error) {
	// Use collaborative filter service to generate recommendations
	return r.collaborativeFilterService.GenerateRecommendations(ctx, customerID, typeArg)
}

// Metadata is the resolver for the metadata field.
func (r *recommendationResolver) Metadata(ctx context.Context, obj *domain.Recommendation) (*model.RecommendationMetadata, error) {
	if obj.Metadata == nil || len(obj.Metadata) == 0 {
		return nil, nil
	}

	var meta domain.RecommendationMeta
	if err := json.Unmarshal(obj.Metadata, &meta); err != nil {
		return nil, fmt.Errorf("failed to unmarshal metadata: %w", err)
	}

	return &model.RecommendationMetadata{
		Algorithm:     meta.Algorithm,
		Confidence:    meta.Confidence,
		BasedOnUsers:  meta.BasedOnUsers,
		SimilarityAvg: meta.SimilarityAvg,
	}, nil
}

// SimilarCustomers is the resolver for the similarCustomers field.
func (r *recommendationResolver) SimilarCustomers(ctx context.Context, obj *domain.Recommendation) ([]string, error) {
	// Return the similar customer IDs stored in the recommendation
	if obj.SimilarCustomers == nil {
		return []string{}, nil
	}
	return obj.SimilarCustomers, nil
}

// Customer returns generated.CustomerResolver implementation.
func (r *Resolver) Customer() generated.CustomerResolver { return &customerResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Recommendation returns generated.RecommendationResolver implementation.
func (r *Resolver) Recommendation() generated.RecommendationResolver {
	return &recommendationResolver{r}
}

type customerResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type recommendationResolver struct{ *Resolver }
