// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"poc-collaborative-filter/internal/domain"
)

type CreateCustomerInput struct {
	Name        string                      `json:"name"`
	Email       *string                     `json:"email,omitempty"`
	Phone       *string                     `json:"phone,omitempty"`
	Segment     domain.CustomerSegment      `json:"segment"`
	Status      domain.CustomerStatus       `json:"status"`
	RiskProfile *domain.CustomerRiskProfile `json:"riskProfile,omitempty"`
	Traits      *CustomerTraitsInput        `json:"traits,omitempty"`
}

type CustomerConnection struct {
	Nodes      []*domain.Customer `json:"nodes"`
	TotalCount int                `json:"totalCount"`
}

type CustomerFilter struct {
	Segment     *domain.CustomerSegment     `json:"segment,omitempty"`
	Status      *domain.CustomerStatus      `json:"status,omitempty"`
	RiskProfile *domain.CustomerRiskProfile `json:"riskProfile,omitempty"`
	Search      *string                     `json:"search,omitempty"`
}

type CustomerTraitsInput struct {
	Personality    []string              `json:"personality,omitempty"`
	Preferences    []string              `json:"preferences,omitempty"`
	Notes          *string               `json:"notes,omitempty"`
	Tags           []string              `json:"tags,omitempty"`
	Properties     []*TraitPropertyInput `json:"properties,omitempty"`
	RelatedPersons []*RelatedPersonInput `json:"relatedPersons,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RecommendationMetadata struct {
	Algorithm     string         `json:"algorithm"`
	Parameters    map[string]any `json:"parameters,omitempty"`
	Confidence    float64        `json:"confidence"`
	BasedOnUsers  int            `json:"basedOnUsers"`
	SimilarityAvg float64        `json:"similarityAvg"`
}

type RelatedPersonInput struct {
	Name         string  `json:"name"`
	Relationship string  `json:"relationship"`
	Phone        *string `json:"phone,omitempty"`
	Email        *string `json:"email,omitempty"`
}

type SimilarCustomer struct {
	Customer        *domain.Customer   `json:"customer"`
	SimilarityScore float64            `json:"similarityScore"`
	Weights         *SimilarityWeights `json:"weights"`
}

type SimilarityWeights struct {
	Personal       float64 `json:"personal"`
	Survey         float64 `json:"survey"`
	ActivityAccess float64 `json:"activityAccess"`
	Transaction    float64 `json:"transaction"`
}

type TraitPropertyInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
	Type  string `json:"type"`
}

type UpdateCustomerInput struct {
	Name        *string                     `json:"name,omitempty"`
	Email       *string                     `json:"email,omitempty"`
	Phone       *string                     `json:"phone,omitempty"`
	Segment     *domain.CustomerSegment     `json:"segment,omitempty"`
	Status      *domain.CustomerStatus      `json:"status,omitempty"`
	RiskProfile *domain.CustomerRiskProfile `json:"riskProfile,omitempty"`
	Traits      *CustomerTraitsInput        `json:"traits,omitempty"`
}
